# Generated by Django 5.2.7 on 2025-11-24 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkModel",
            fields=[
                (
                    "atv_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único da atividade",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID da Atividade",
                    ),
                ),
                (
                    "atv_name",
                    models.CharField(
                        help_text="Nome da atividade de homework",
                        max_length=30,
                        verbose_name="Nome da Atividade",
                    ),
                ),
                (
                    "atv_description",
                    models.CharField(
                        blank=True,
                        help_text="Descrição opcional da atividade de homework",
                        max_length=255,
                        null=True,
                        verbose_name="Descrição da Atividade",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora limite para entrega da atividade",
                        null=True,
                        verbose_name="Data de Entrega",
                    ),
                ),
                (
                    "atv_created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a atividade foi criada",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "atv_updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização da atividade",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Sala à qual esta atividade pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="classroom.classroommodel",
                        verbose_name="Sala",
                    ),
                ),
            ],
        ),
    ]
