# Generated by Django 5.2.7 on 2025-12-05 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homework", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkmodel",
            name="professor",
            field=models.ForeignKey(
                help_text="Usuário que criou a atividade",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
