# Generated by Django 5.2.7 on 2025-11-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homeworkmodel",
            old_name="atv_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="homeworkmodel",
            old_name="atv_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="homeworkmodel",
            old_name="atv_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="homeworkmodel",
            old_name="atv_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="homeworkmodel",
            old_name="atv_updated_at",
            new_name="updated_at",
        ),
    ]
