# Generated by Django 5.2.7 on 2025-11-24 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassroomModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único da sala",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID da Sala",
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        blank=True,
                        help_text="Código único de 6 dígitos para a sala",
                        null=True,
                        unique=True,
                        verbose_name="Código da Sala",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da sala de aula",
                        max_length=100,
                        verbose_name="Nome da Sala",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da sala de aula",
                        null=True,
                        verbose_name="Descrição da Sala",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a sala foi criada",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização da sala",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Status atual da sala (ativa ou inativa)",
                        max_length=10,
                        verbose_name="Status da Sala",
                    ),
                ),
            ],
        ),
    ]
