# Generated by Django 5.2.7 on 2025-12-05 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroommodel",
            name="professor",
            field=models.ForeignKey(
                help_text="Usuário que criou a sala",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Professor Criador",
            ),
        ),
        migrations.AddField(
            model_name="classroommodel",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lista de alunos matriculados na sala",
                related_name="enrolled_classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alunos da Sala",
            ),
        ),
    ]
