# Generated by Django 5.2.7 on 2025-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroommodel",
            name="code",
            field=models.TextField(
                blank=True,
                help_text="Código único de 6 dígitos para a sala",
                null=True,
                unique=True,
                verbose_name="Código da Sala",
            ),
        ),
    ]
