# Generated by Django 5.2.7 on 2025-11-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0003_alter_classroommodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroommodel",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Código único de 6 caracteres para a sala",
                max_length=6,
                null=True,
                unique=True,
                verbose_name="Código da Sala",
            ),
        ),
    ]
